import Head from 'next/head'
// @ts-ignore

import styles from '../styles/Home.module.css'
import Web3 from 'web3';
import { useContext, useEffect} from 'react';
// @ts-ignore
import signTypedData from './components/signTypeData';
import React from 'react';
import { ACTION_TYPE } from './_app';
import { MetaContext } from './_app';
import { getToken } from './components/gettoken';
import { msgData } from './data/data';
import { typedData } from './data/typeddata';
import { mintNft } from './components/nftmint';


export default function Home() {


const {dispatch, state} = useContext(MetaContext)

const {account, web3} = state ;






function loadMeta() {
  // @ts-ignore
  const {ethereum} = window;
  console.log(ethereum)
  if(ethereum && ethereum.isMetaMask){
    
   dispatch({
    type: ACTION_TYPE.SET_ACCOUNT,
    payload: {account: `${ethereum['selectedAddress']}`}
   }) 
console.log('Ethereum successfully detected!', account)
    const web3 = new Web3(ethereum)
    // @ts-ignore
   
    dispatch({
      type: ACTION_TYPE.SET_WEB3,
      payload: {web3 : web3}
    })
  }
}
useEffect(()=> {

  // @ts-ignore
  if ((window).ethereum){
    loadMeta()

  }else{
    window.addEventListener('ethereum#initialized', loadMeta, {
      once: true,
    })
    // @ts-ignore
    setTimeout(loadMeta, 3000)
  }
    },[])
    const loadMetamask = async () => {
      // You need to await for user response on the metamask popup dialog
      // @ts-ignore
      const accounts = await ethereum.request({ method: 'eth_requestAccounts' });
      if(accounts){
       
        dispatch({
          type: ACTION_TYPE.SET_ACCOUNT,
          payload: {account: `${accounts[0]}`}
         }) 
      }
    }

    


    async function mint() {

     const tokenId = await getToken(web3, account)
     console.log(tokenId);


    const msg = msgData(tokenId.tokenId, account);

    console.log('msg', msg);

     
  const dataStructure = await typedData(web3,msg)
    console.log("datastructure",dataStructure);

// const chain  = await  web3.currentProvider.request({
//   method: "eth_chainId",
//   from: account
// })
// console.log(chain);


// const getacc = await web3.utils.checkAddressChecksum(account)
// console.log(getacc);


    // @ts-ignore
  const sign = await signTypedData(web3, account, dataStructure)
  console.log(sign);
  const sign_obj =  {"signatures" : [sign.signature]}
  const data = {...msg, ...sign_obj}




// const add = await web3.utils.checkAddressChecksum(sign)
// console.log(add);

 await mintNft(data)





    }


  return (
    <div className={styles.container}>
      <Head>
        <title>Myraah mint</title>
        <meta name="Myraah-mint" content="Generated by Myraah" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
         <h3>Connect to metamask</h3> 
          <button 
// @ts-ignore
          type='click' onClick={loadMetamask}>Connect</button>
          <button 
// @ts-ignore
          type='click' onClick={mint}>Mint</button>
          <h1>{account}</h1>
        </div>
        </main>
    </div>
  )
}

